NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('posts/', include('news.urls')),
   path("accounts/", include("allauth.urls")),
]

NewsPaper/news/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostCreate, PostUpdate, PostDelete, PostSearch, CategoryListView, subscribe, unsubscribe
from django.views.decorators.cache import cache_page

urlpatterns = [
   path('', cache_page(60)(PostsList.as_view()), name='posts_list'),
   path('<int:pk>', cache_page(60*5)(PostDetail.as_view()), name='post_detail'),
   path('search/', PostSearch.as_view(), name='post_search'),
   path('create/', PostCreate.as_view(), name='post_create'),
   path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
   path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
   path('categories/<int:pk>/unsubscribe', unsubscribe, name='unsubscribe'),
]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)


    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

    def __str__(self):
        return f'{self.authorUser}'


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)



class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper/templates/category_list.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}


{% block content %}
<h1 class="text-center">Все посты категории {{ category }}</h1>

    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}
    {% if not is_not_subscriber %}
        <p class="text-center"><a href="{% url 'unsubscribe' category.id %}" class="btn btn-secondary btn-sm">Отписаться</a></p>
    {% endif %}

<p class="text-center"><a href="{% url 'posts_list' %}" class="btn btn-secondary btn-sm">К постам</a></p>

<hr>
   {% if perms.news.add_post %}
   <a href="{% url 'post_create' %}">Создать пост</a>
   {% endif %}
<hr>

   {% if category_posts_list %}
       <table>
            <tr>
                <td>
                    Заголовок
                </td>
                <td>
                    Дата публикации
                </td>
                <td>
                   Текст
                </td>
                <td>
                   Категория
                </td>
                {% if perms.news.change_post or perms.news.delete_post %}
                <td>
                    Действия
                </td>
                {% endif %}
            </tr>
            {% for post in category_posts_list %}
            <tr>
                <td>
                    <a class="nav-link" href="{% url 'post_detail' post.id %}">{{ post.title|censor }}</a>
                </td>
                <td>
                    {{ post.dateCreation | date:'d M Y' }}
                </td>
                <td>
                    {{ post.text|censor|truncatechars:21 }}
                </td>
                <td>
                    {% for category in post.category.all %}
                       <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                    {% endfor %}
                </td>
                <td>
                    {% if perms.news.change_post %}
                    <a href="{% url 'post_update' pk=post.id %}"><u>Изменить</u></a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a href="{% url 'post_delete' post.id %}"><u>Удалить</u></a>
                    {% endif %}
                </td>
            </tr>
           {% endfor %}
       </table>

   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}

<p class="text-center"><a href="{% url 'posts_list' %}" class="btn btn-secondary btn-sm">К постам</a></p>

<table>
    <tr>
        <td>
            Заголовок
        </td>
        <td>
            Текст
        </td>
        <td>
            Дата загрузки
        </td>
        <td>
            Категория
        </td>
    </tr>
    <tr>
        <td>
            {{ post.title|censor }}
        </td>
        <td>
            {{ post.text|censor }}
        </td>
        <td>
            {{ post.dateCreation|date:'d M Y' }}
        </td>
        <td>
            {% for category in post.category.all %}
            <a href="{% url 'category_list' category.id %}">{{ category }}</a>
            {% endfor %}
        </td>
    </tr>

</table>
{% endblock content %}

NewsPaper/templates/post_created_email.html
<!DOCTYPE html>
<html lang="eng">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новая статья <a href="{{ link }}">статья</a> в твоем любимом разделе!</h2>
<p>{{ text }}</p>
</body>
</html>

NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Вы уверены, что хотите удалить "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
   <h1>Все новости </h1>
   <h3>{{ time_now|date:'d M Y' }}</h3>
   <hr>

   {% if perms.news.add_post %}
   <a href="{% url 'post_create' %}">Создать пост</a>
   {% endif %}

   {% if posts %}
       <table>
           <tr>
               <td>
                   Заголовок
               </td>
               <td>
                   Дата публикации
               </td>
               <td>
                   Текст
               </td>
               <td>
                   Категория
               </td>
               {% if perms.news.change_post or perms.news.delete_post %}
               <td>
                   Действия
               </td>
               {% endif %}
           </tr>
           {% for post in posts %}
           <tr>
               <td>
                   <a class="nav-link" href="{% url 'post_detail' post.id %}">{{ post.title|censor }}</a>
               </td>
               <td>
                   {{ post.dateCreation }}
               </td>
               <td>
                   {{ post.text|censor|truncatechars:21 }}
               </td>
               <td>
                   {% for category in post.category.all %}
                   <a href="{% url 'category_list' category.id %}">{{ category }}</a>
                   {% endfor %}
               </td>
               <td>
                    {% if perms.news.change_post %}
                    <a href="{% url 'post_update' pk=post.id %}"><u>Изменить</u></a>
                    {% endif %}
                    {% if perms.news.delete_post %}
                    <a href="{% url 'post_delete' post.id %}"><u>Удалить</u></a>
                    {% endif %}
                </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Постов нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
   <h1>Все новости </h1>

   <form action=""  method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Search">
   </form>

   <hr>
   <h3>{{ time_now|date:'d M Y' }}</h3>
   {% if posts %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
           </tr>
           {% for post in posts %}
           <tr>
               <td><a class="nav-link" href="{% url 'post_detail' post.id %}">{{ post.title|censor }}</a></td>
               <td>{{ post.dateCreation }}</td>
               <td>{{ post.text|censor|truncatechars:21 }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>По выбранным критериям постов нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1 class="text-center">{{ message }} {{category }}</h1>
<p class="text-center"><a href="{% url 'posts_list' %}" class="btn btn-secondary btn-sm">К постам</a></p>
{% endblock %}

NewsPaper/templates/unsubscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1 class="text-center">{{ message }} {{category }}</h1>
<p class="text-center"><a href="{% url 'posts_list' %}" class="btn btn-secondary btn-sm">К постам</a></p>
{% endblock %}

NewsPaper/templates/weekly_post.html
<!DOCTYPE html>
<html lang="eng">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новые посты за последнюю неделю!</h2>
<ul>
    {% for post in posts %}
        <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
<p>{{ text }}</p>
</body>
</html>